site_name: Dahlia Oopzs Torah Notes
site_url: https://dahliyah.github.io
site_description: Project documentation with Markdown
site_author: Dahlia (Oopzs)
repo_url: https://dahliyah.github.io


theme:
    name: material
    custom_dir: docs/overrides
    locale: en
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    features:
        - navigation.footer
        - navigation.instant
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.tabs
        - navigation.sections
        - navigation.path
        - toc.integrate
    palette: 
        scheme: slate
        primary: light green

 
extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCVh_qkKF2ecK8cBDADmuojA
  generator: false


nav:
    - Home: index.md
    - Biblical Cosmology:
        - Earth: Biblical Cosmology/Earth.md
        - Firmament: Biblical Cosmology/Firmament.md
        - NASA: Biblical Cosmology/NASA.md
    - Calendar:
        - Feasts:
            - How do we celebrate it?: Calendar/Feasts/How do we celebrate it.md
    - Laws:
        - Clean and Unclean Foods: Law/Commandments/Ourselves/Clean and Unclean Foods.md
        - Commandments: Law/Commandments/613 Commandments.md
        - Eternal Torah: Law/Eternal Torah.md
        - Marriage: Law/Marriage.md
        - Priesthood: Law/Priesthood.md
        - Purity Laws: Law/Commandments/Ourselves/Purity Laws.
        - The Law: Law/The Law.md
    - Canon:
        - Bible Canon: Canon/Bible Canon.md
        - Septuagint: Canon/Septuagint Text Family.md
    - The Trinity:
        - The Trinity: The Trinity/The Trinity.md
        - Who is Yahusha (Jesus): The Trinity/Who is Yahusha (Jesus).md
    - Bodies:
        - Living Soul: Bodies/Living Soul.md
    - Book of Enoch:
        - Enoch Study: Book of Enoch/Enoch Study.md
    - The World:
        - New Age: The World/New Age.md
        - Dispensationalism: The World/Dispensationalism.md
    - Timelines:
        - Events: Timelines/Events.md
    - Fallacies: Fallacies and Argument Tactics.md
    - Donate: https://cash.app/$dahlialo
    - Extras:
        - Resources: Links to Resources.md

        
extra_css:
    - css/extra.css

markdown_extensions:
    - callouts
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - admonition
    - pymdownx.betterem
    - full_yaml_metadata
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.escapeall
    - pymdownx.extra
    - pymdownx.highlight:
        line_spans: __span
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.pathconverter
    - pymdownx.progressbar
    - pymdownx.saneheaders
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.striphtml
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - footnotes
    - toc:
        permalink: 
    - attr_list
    - md_in_html
    - def_list
    - tables
    - pymdownx.highlight:
        use_pygments: false
    - pymdownx.snippets
    - pymdownx.superfences
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs
    - mkdocs-click
    - pymdownx.arithmatex
    - pymdownx.b64
    - pymdownx.superfences:
       custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


copyright: Copyright &copy; 2022 - 2023 Dahlia Love / Setapart.top 


hooks:
    - docs/hooks.py

plugins:
    - pub-obsidian
    - mkdocs-backlinks
    - obsidian-bridge
    - tags
    - include-markdown
    - search
    - autorefs
    - callouts
    - table-reader
    - rss
    - search
    - title-casing
    - git-revision-date-localized
    - git-revision-date
    - literate-nav:
        nav_file: README.md
        implicit_index: true
    - mkdocstrings:
        handlers:
          python:
            options:
              docstring_section_style: list
              members_order: source
              show_root_heading: true
              show_source: false
              show_signature_annotations: true

watch:
    - mkdocs
